### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'config['urls']['loginUrl']')

### ISSUE THREAD

**Issue by shuiqlazam** [stardothosting/facebook-purge#3]
First a comment on an issue i resolved, please update your guide to explain where to obtain the config.json file needed by the script.  I found the config.json as shown below and copied to my bin directory.

~/node_modules/casperjs/tests/sample_modules$ cp config.json ~/node_modules/casperjs/bin

Now for the issue - when i run the script, I get the following error - 
TypeError: undefined is not an object (evaluating 'config['urls']['loginUrl']')

This relates to this line in the script or the actual call of the VAR

var wallUrl = config['urls']['loginUrl'] + username.split('@')[0];  // Assuming the email id is your facebook page vanity url.

casper.start().thenOpen(config['urls']['loginUrl'], function() {
    console.log(username);
    console.log("Facebook website opened");
});

Any thougths on why this issue is occuring?

Thanks
Shui

**Comment by stardothosting** [comment]
Create a file config.json and add the snippet below to it

`{
    "urls" : {
        "loginUrl" : "https://www.facebook.com/",
        "eventsUrl" : "https://www.facebook.com/events/birthdays/"
    }
}`

I will add this to the repo

**Comment by shuiqlazam** [comment]
yeah, i made a dumb user mistake - i didnt clone into the GIT.

git clone https://github.com/stardothosting/facebook-purge

once i did that, the correct JSON file downloaded.  thanks!
