### ISSUE TITLE
Script is working to point of edit

### ISSUE THREAD

**Issue by shuiqlazam** [stardothosting/facebook-purge#4]
The script is working beautifully when i feed it a valid post_id and user_id - i get the screen grab showing the edit function is enabled -  it posts the giberish (which i added more console logging to confirm) - it then saves the post without changing the text to the giberish.

Once we figure that out, even using a looping structure, how are we going to generate the long random post ids?  It's like a brute force attack..

Still more interested in why the post of giberish save is not working...

![afterlogin5](https://user-images.githubusercontent.com/37935062/38150163-49f1501a-3423-11e8-80e1-e4d191e11e08.png)
![after_post_edit](https://user-images.githubusercontent.com/37935062/38150164-49f1589e-3423-11e8-90a1-4fe814182681.png)

shui

**Comment by stardothosting** [comment]
This is where i got stuck for the longest time. I played around with the wait time and submitting the edit text in a try.evaluate jQuery value versus casper.sendKeys.

The sendKeys worked for me previously, you might want to try that instead. But I think something is happening behind the scenes that is causing the variable results perhaps? Going through the mouse click breakpoints in google chrome gave some clues, but short of telling CasperJS to bash the mouse until it saved is basically how I got it working.

**Comment by z5Q46L6bSY1W** [comment]
Same issue for me. Login was successful. Navigating to and opening the post was successful. However, the post remains the same in both screenshots.

casperjs 1.1.4

**Comment by stardothosting** [comment]
Even with the most recent commit today? I changed the selector for the mouse down/up/over/click events to use the data attribute of the edit button instead of the id, as that changes too often.

**Comment by z5Q46L6bSY1W** [comment]
Actually, I ran it again and it worked!

**Comment by stardothosting** [comment]
Yeah here's what changed

`+    this.mouse.move('button[data-sigil="post-edit-save-button"]');
+    this.mouse.down('button[data-sigil="post-edit-save-button"]');
+    this.mouse.up('button[data-sigil="post-edit-save-button"]');
+    `this.mouse.click('button[data-sigil="post-edit-save-button"]');``

**Comment by shuiqlazam** [comment]
New script is working for me now.  This is great!
